Subject/Models/PostShop.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PostShop
    {
        [DisplayName("投稿編號")]
        public int PostNumber { get; set; }

        [DisplayName("店家名稱")]
        [Required(ErrorMessage = "請填寫店家名稱")]
        public string PostName { get; set; }

        [DisplayName("區域")]
        public string PostDistrict { get; set; }

        [DisplayName("地址")]
        public string PostAdress { get; set; }

        [DisplayName("營業時間")]
        public string PostTime { get; set; }

        [DisplayName("電話")]
        public string PostPhone { get; set; }

        [DisplayName("網站")]
        public string PostWeb { get; set; }

        [DisplayName("有插座")]
        public Nullable<bool> PostOutlet { get; set; }

        [DisplayName("有Wifi")]
        public Nullable<bool> PostWifi { get; set; }

        [DisplayName("限時間")]
        public Nullable<bool> PostLimitedTime { get; set; }

        [DisplayName("可訂位")]
        public Nullable<bool> PostOrder { get; set; }

        [DisplayName("會員")]
        public int UserNumber { get; set; }

        [DisplayName("投稿日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> PostDate { get; set; }

        [DisplayName("通過日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> PassDate { get; set; }

        [DisplayName("管理員")]
        public Nullable<int> AdmNumber { get; set; }
    
        public virtual Adm Adm { get; set; }
        public virtual Users Users { get; set; }
    }
}

Subject/Controllers/PostShopsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Subject.Models;

namespace Subject.Controllers
{

    [LoginCheck]
    public class PostShopsController : Controller
    {
        private SpecialSubjectEntities db = new SpecialSubjectEntities();
        SetData sd = new SetData();

        // GET: PostShops
        public ActionResult Index()
        {
            var postShop = db.PostShop.Include(p => p.Adm).Include(p => p.Users);
            return View(postShop.ToList());
        }

        // GET: PostShops/Details/5
        public ActionResult _Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PostShop postShop = db.PostShop.Find(id);
            if (postShop == null)
            {
                return HttpNotFound();
            }
            return PartialView(postShop);
        }

        // GET: PostShops/Create
        public ActionResult _Create()
        {
            ViewBag.AdmNumber = new SelectList(db.Adm, "AdmNumber", "AdmNumber");
            ViewBag.UserNumber = new SelectList(db.Users, "UserNumber", "UserNumber");
            return PartialView();
        }

        // POST: PostShops/Create
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PostShop postShop)
        {
            if (ModelState.IsValid)
            {
                string sql = "insert into PostShop(PostName,PostDistrict,PostAdress,PostTime,PostPhone,PostWeb,PostOutlet," +
                    "PostWifi,PostLimitedTime,PostOrder,UserNumber,AdmNumber)values(@PostName,@PostDistrict,@PostAdress," +
                    "@PostTime,@PostPhone,@PostWeb,@PostOutlet,@PostWifi,@PostLimitedTime,@PostOrder,@UserNumber,@AdmNumber)";
                List<SqlParameter> list = new List<SqlParameter>
                {
                    new SqlParameter("PostName",postShop.PostName),
                    new SqlParameter("PostDistrict",postShop.PostDistrict),
                    new SqlParameter("PostAdress",postShop.PostAdress),
                    new SqlParameter("PostTime",postShop.PostTime),
                    new SqlParameter("PostPhone",postShop.PostPhone),
                    new SqlParameter("PostWeb",postShop.PostWeb),
                    new SqlParameter("PostOutlet",postShop.PostOutlet),
                    new SqlParameter("PostWifi",postShop.PostWifi),
                    new SqlParameter("PostLimitedTime",postShop.PostLimitedTime),
                    new SqlParameter("PostOrder",postShop.PostOrder),
                    new SqlParameter("UserNumber",postShop.UserNumber),
                    new SqlParameter("AdmNumber",postShop.AdmNumber)
                };

                sd.executeSql(sql,list);
                return RedirectToAction("Index");
               
            }

            ViewBag.AdmNumber = new SelectList(db.Adm, "AdmNumber", "AdmNumber", postShop.AdmNumber);
            ViewBag.UserNumber = new SelectList(db.Users, "UserNumber", "UserNumber", postShop.UserNumber);
            return View(postShop);
        }

        // GET: PostShops/Edit/5
        
        public ActionResult _Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PostShop postShop = db.PostShop.Find(id);
            if (postShop == null)
            {
                return HttpNotFound();
            }
            ViewBag.AdmNumber = new SelectList(db.Adm, "AdmNumber", "AdmNumber", postShop.AdmNumber);
            ViewBag.UserNumber = new SelectList(db.Users, "UserNumber", "UserNumber", postShop.UserNumber);
            return PartialView(postShop);
        }

        // POST: PostShops/Edit/5
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PostShop postShop)
        {
            if (ModelState.IsValid)
            {
                int id = ((Adm)Session["adm"]).AdmNumber;
                var adms = db.Adm.Find(id);

                string sql = "update PostShop set PassDate=@PassDate,AdmNumber=@AdmNumber " +
                    "where PostNumber=@PostNumber";

                List<SqlParameter> list = new List<SqlParameter>
                {
                    new SqlParameter("PassDate",postShop.PassDate),
                    new SqlParameter("AdmNumber",adms.AdmNumber),
                    new SqlParameter("PostNumber",postShop.PostNumber)
                };

                sd.executeSql(sql, list);
                return RedirectToAction("Index");
            }
            
                ViewBag.AdmNumber = new SelectList(db.Adm, "AdmNumber", "AdmNumber", postShop.AdmNumber);
                ViewBag.UserNumber = new SelectList(db.Users, "UserNumber", "UserNumber", postShop.UserNumber);
                return View(postShop);
            
            
        }

        // GET: PostShops/Delete/5
        public ActionResult _Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PostShop postShop = db.PostShop.Find(id);
            if (postShop == null)
            {
                return HttpNotFound();
            }
            return PartialView(postShop);
        }

        // POST: PostShops/Delete/5
        [HttpPost, ActionName("_Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PostShop postShop = db.PostShop.Find(id);
            db.PostShop.Remove(postShop);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Subject/Views/PostShops/Index.cshtml
@model IEnumerable<Subject.Models.PostShop>

@{
    ViewBag.Title = "Index";
}


<h2 class="mt-3 text-center">投稿店家</h2>


<table class="table table-hover table-responsive-lg mt-3">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PostNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PassDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AdmNumber)
        </th>

        <th>管理</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PostNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Users.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PassDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adm.AdmAccount)
            </td>

            <td>
                <button type="button" id="@item.PostNumber" class="btn btn-success btn-sm" data-toggle="modal" data-target="#showDetailModal" onclick="getDetailData(event)">
                    <i class="bi bi-journal-text" id="@item.PostNumber"></i>
                </button>
                <button type="button" id="@item.PostNumber" class="btn btn-primary btn-sm disabled" data-toggle="modal" data-target="#showEditModal" onclick="getEditData(event)">
                    <i class="bi bi-check-square" id="@item.PostNumber"></i>
                </button>
                <button type="button" id="@item.PostNumber" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#showDeleteModal" onclick="getDeleteData(event)">
                    <i class="bi bi-trash3" id="@item.PostNumber"></i>
                </button>
            </td>
        </tr>
    }

</table>

<div class="modal fade" id="showDetailModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <div class="text-dark mt-2 ml-2"><h5>詳細資料</h5></div>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="showEditModal" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <div class="text-dark mt-2 ml-2"><h5>確認通過請填上通過日期</h5></div>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="showDeleteModal" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <div class="text-dark mt-2 ml-2"><h5>確定要刪除嗎?</h5></div>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $('#AddForm').click(function () {
            $('#AddPostShop').fadeToggle(800);
        });

        function getDetailData(evt) {
            $('#showDetailModal .modal-body').load("/PostShops/_Details/" + evt.target.id);
        }

        function getEditData(evt) {
            $('#showEditModal .modal-body').load("/PostShops/_Edit/" + evt.target.id);
        }

        function getDeleteData(evt) {
            $('#showDeleteModal .modal-body').load("/PostShops/_Delete/" + evt.target.id);
        }
    </script>
}

Subject/Views/PostShops/_Create.cshtml
@model Subject.Models.PostShop

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create","PostShops",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.UserNumber)
    <div class="form-group">
        @Html.LabelFor(model => model.PostName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PostName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PostName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PostDistrict, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PostDistrict, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PostDistrict, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PostAdress, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PostAdress, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PostAdress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PostTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PostTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PostTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PostPhone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PostPhone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PostPhone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PostWeb, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PostWeb, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PostWeb, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PostOutlet, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.PostOutlet)
                @Html.ValidationMessageFor(model => model.PostOutlet, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PostWifi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.PostWifi)
                @Html.ValidationMessageFor(model => model.PostWifi, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PostLimitedTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.PostLimitedTime)
                @Html.ValidationMessageFor(model => model.PostLimitedTime, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PostOrder, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.PostOrder)
                @Html.ValidationMessageFor(model => model.PostOrder, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserNumber, "UserNumber", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UserNumber", (IEnumerable<SelectListItem>)ViewBag.UserNumber, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UserNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.PostDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PassDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PassDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PassDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.AdmNumber, "AdmNumber", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("AdmNumber", (IEnumerable<SelectListItem>)ViewBag.AdmNumber, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AdmNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="新增" class="btn btn-default" />
        </div>
    </div>
</div>
}



<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Subject/Views/PostShops/_Delete.cshtml
@model Subject.Models.PostShop

@{
    ViewBag.Title = "Delete";
}

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PostNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostNumber)
        </dd>
    </dl>

    @using (Html.BeginForm("_Delete", "PostShops", FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="刪除" class="btn btn-danger" />
            @*@Html.ActionLink("Back to List", "Index")*@
        </div>
    }
</div>

Subject/Views/PostShops/_Details.cshtml
@model Subject.Models.PostShop

@{
    ViewBag.Title = "Details";
    var c = "";
    var p = Model.PostPhone;
    var d = Model.PostDistrict;
    var a = Model.PostAdress;
}

<style>
    #TimeTitle {
        background-color: #f8f9fa;
    }
</style>

<div class="card">
    <div class="card-header">
        <h5>
            @Html.DisplayFor(model => model.PostName)
        </h5>
    </div>
    <div class="card-body row">
        <div class="col-7">
            <div>
                @Html.DisplayNameFor(model => model.PostPhone):
                <span class="@(c=Model.PostPhone == null? "text-black-50" : "")">@(c=Model.PostPhone == null? "無" : p)</span>
            </div>
            <div>
                @Html.DisplayNameFor(model => model.PostAdress):
                <span class="@(Model.PostDistrict != null && Model.PostAdress != null? "":"text-black-50")">@(Model.PostDistrict != null && Model.PostAdress != null? "高雄市"+d+a:"無")</span>
            </div>
            <div>
                @Html.DisplayNameFor(model => model.PostWeb): <a href="@Html.DisplayFor(model => model.PostWeb)">@Html.DisplayFor(model => model.PostWeb)</a>
            </div>
            <hr />

            <div class="row p-3">
                <div class="col-5">
                    @Html.DisplayNameFor(model => model.PostOutlet):
                    <span class="p-3  @(c = Model.PostOutlet == null ? "text-black-50" : c=Model.PostOutlet == true? "text-primary":"text-warning")">@(c = Model.PostOutlet == null ? "未知" : c = Model.PostOutlet == true ? "Yes" : "No")</span>
                </div>
                <div class="col-5">
                    @Html.DisplayNameFor(model => model.PostWifi):
                    <span class="p-3 @(c = Model.PostWifi == null ? "text-black-50" :c=Model.PostWifi == true? "text-primary":"text-warning")">@(c = Model.PostWifi == null ? "未知" : c = Model.PostWifi == true ? "Yes" : "No")</span>
                </div>
            </div>
            <div class="row p-3">
                <div class="col-5">
                    @Html.DisplayNameFor(model => model.PostLimitedTime):
                    <span class="p-3 @(c = Model.PostLimitedTime == null ? "text-black-50" :c=Model.PostLimitedTime == true? "text-primary":"text-warning")">@(c = Model.PostLimitedTime == null ? "未知" : c = Model.PostLimitedTime == true ? "Yes" : "No")</span>
                </div>
                <div class="col-5">
                    @Html.DisplayNameFor(model => model.PostOrder):
                    <span class="p-3 @(c = Model.PostOrder == null ? "text-black-50" :c=Model.PostOrder == true? "text-primary":"text-warning")">@(c = Model.PostOrder == null ? "未知" : c = Model.PostOrder == true ? "Yes" : "No")</span>
                </div>
            </div>


        </div>
        <div class="col-5 text-center" style="border-left: 1px solid #e0e0e0">
            <div>
                <div class="alert" id="TimeTitle">@Html.DisplayNameFor(model => model.PostTime)</div>
                @if (Model.PostTime == null)
                {
                    <span class="text-black-50">未知</span>
                }
                else
                {
                    <div>@Html.Raw(Model.PostTime.ToString().Replace(" ", "<br>"))</div>
                }
            </div>
        </div>

        <div class="col-2">


        </div>
    </div>
</div>

Subject/Views/PostShops/_Edit.cshtml
@model Subject.Models.PostShop

@{
    ViewBag.Title = "Edit";
}


@using (Html.BeginForm("Edit", "PostShops", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.PostNumber)
    @Html.HiddenFor(model => model.PostName)
    @Html.HiddenFor(model => model.UserNumber)

    <div class="form-group">
        @Html.LabelFor(model => model.PassDate, htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PassDate, new { htmlAttributes = new { @class = "form-control", type = "date" } })
            @Html.ValidationMessageFor(model => model.PassDate, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.AdmNumber, "AdmNumber", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AdmNumber", (IEnumerable<SelectListItem>)ViewBag.AdmNumber, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AdmNumber, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="更新" class="btn btn-light" />
        </div>
        <span class="text-danger">@ViewBag.Msg</span>
    </div>
</div>
}


<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>