Subject/Controllers/AdmsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Subject.Models;
using System.Configuration;
using Subject.ViewModels;

namespace Subject.Controllers
{
    [LoginCheck]
    public class AdmsController : Controller
    {
        private SpecialSubjectEntities db = new SpecialSubjectEntities();
        SetData sd = new SetData();

       
        public ActionResult Index()
        {
            return View(db.Adm.ToList());
        }

        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adm adm = db.Adm.Find(id);
            if (adm == null)
            {
                return HttpNotFound();
            }
            return View(adm);
        }

       
        public ActionResult _Create()
        {
            return PartialView();
        }

        // POST: Adms/Create
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Adm adm)
        {
            if (ModelState.IsValid)
            {
                string sql = "insert into Adm(AdmAccount,AdmPsaaword)" +
                    "values(@AdmAccount,@AdmPsaaword)";

                List<SqlParameter> list = new List<SqlParameter>
                {
                    new SqlParameter("AdmAccount",adm.AdmAccount),
                    new SqlParameter("AdmPsaaword",adm.AdmPsaaword)
                };

                sd.executeSql(sql, list);

                return RedirectToAction("Index");
            }

            return View(adm);
        }

    
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adm adm = db.Adm.Find(id);
            if (adm == null)
            {
                return HttpNotFound();
            }
            return View(adm);
        }

        // POST: Adms/Edit/5
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AdmNumber,AdmAccount,AdmPsaaword")] Adm adm)
        {
            if (ModelState.IsValid)
            {
                db.Entry(adm).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(adm);
        }


        public ActionResult _Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adm adm = db.Adm.Find(id);
            if (adm == null)
            {
                return HttpNotFound();
            }
            return PartialView(adm);
        }

    
        [HttpPost, ActionName("_Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Adm adm = db.Adm.Find(id);
            db.Adm.Remove(adm);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [LoginCheck(flag = false)]
        public ActionResult Login()
        {
            return View();
        }

        [LoginCheck(flag = false)]
        [HttpPost]
        public ActionResult Login(VMLogin vMLogin)
        {
            string password = BR.getHashPassword(vMLogin.Password);

            var adm = db.Adm.Where(m => m.AdmAccount == vMLogin.Account && m.AdmPsaaword == vMLogin.Password).FirstOrDefault();

            if (adm == null)
            {
                ViewBag.ErrMsg = "帳號或密碼有誤";
                return View(vMLogin);
            }

            Session["adm"] = adm;
            return RedirectToAction("AfterLogin");
        }

  
        public ActionResult Logout()
        {
            Session["adm"] = null;
            return RedirectToAction("Login");
        }

        public ActionResult AfterLogin()
        {
            return View();
        }



    }
}

Subject/Controllers/PaysController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Subject.Models;

namespace Subject.Controllers
{
    [LoginCheck]
    public class PaysController : Controller
    {
        private SpecialSubjectEntities db = new SpecialSubjectEntities();
        SetData sd = new SetData();

        // GET: Pays
        public ActionResult Index()
        {
            return View(db.Pay.ToList());
        }

        // GET: Pays/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pay pay = db.Pay.Find(id);
            if (pay == null)
            {
                return HttpNotFound();
            }
            return View(pay);
        }

        // GET: Pays/Create
        public ActionResult _Create()
        {
            return PartialView();
        }

        // POST: Pays/Create
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pay pay)
        {
            if (ModelState.IsValid)
            {
                string sql = "insert into Pay(PayType)values(@PayType)";

                List<SqlParameter> list = new List<SqlParameter>
                {
                    new SqlParameter("PayType",pay.PayType)
                };

                sd.executeSql(sql,list);
                return RedirectToAction("Index");
            }

            return View(pay);
        }

        // GET: Pays/Edit/5
        public ActionResult _Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pay pay = db.Pay.Find(id);
            if (pay == null)
            {
                return HttpNotFound();
            }
            return PartialView(pay);
        }

        // POST: Pays/Edit/5
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Pay pay)
        {
            string sql = "update Pay set PayType=@PayType where PayNumber=@PayNumber";

            List<SqlParameter> list = new List<SqlParameter>
            {
                new SqlParameter("PayNumber",pay.PayNumber),
                new SqlParameter("PayType",pay.PayType)
            };

            try
            {
                sd.executeSql(sql,list);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ViewBag.Msg=ex.Message;
                return View(pay);
            }

            //if (ModelState.IsValid)
            //{
            //    db.Entry(pay).State = EntityState.Modified;
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}
            //return View(pay);
        }

        // GET: Pays/Delete/5
        public ActionResult _Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pay pay = db.Pay.Find(id);
            if (pay == null)
            {
                return HttpNotFound();
            }
            return PartialView(pay);
        }

        //POST: Pays/Delete/5
        [HttpPost, ActionName("_Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pay pay = db.Pay.Find(id);
            db.Pay.Remove(pay);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Subject/Controllers/ShopsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Subject.Models;

namespace Subject.Controllers
{
    [LoginCheck]
    public class ShopsController : Controller
    {
        private SpecialSubjectEntities db = new SpecialSubjectEntities();
        SetData sd = new SetData();

        // GET: Shops
        public ActionResult Index()
        {
            var shop = db.Shop.Include(s => s.Adm);
            return View(shop.ToList());
        }

        // GET: Shops/Details/5
        public ActionResult _Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shop shop = db.Shop.Find(id);
            if (shop == null)
            {
                return HttpNotFound();
            }

            Session["shop"] = shop;
            return PartialView(shop);
        }

        /*[ChildActionOnly]*/  //子Action //就不能在網址上打id查詢了  //只能當partialview
        public ActionResult _MenuDetail(int id)
        {
            return PartialView(db.ShopMenu.Where(m => m.ShopNumber == id).ToList());
        }

        public ActionResult _TagDetail(int id)
        {
            return PartialView(db.ShopTag.Where(m => m.ShopNumber == id).ToList());
        }


        public ActionResult _PayDetail(int id)
        {
            return PartialView(db.ShopPay.Where(m => m.ShopNumber == id).ToList());
        }

        public ActionResult _ImageDetail(int id)
        {
            return PartialView(db.ShopImage.Where(m => m.ShopNumber == id).ToList());
        }

        //[LoginCheck(flag = false)]
        public FileContentResult GetPhoto(int id)
        {
            var photo = db.ShopImage.Find(id);
            if (photo != null)
                return File(photo.ShopImage1, "image/jpeg");
            return null;

        }

        // GET: Shops/Create
        
        public ActionResult _Create()
        {
            ViewBag.AdmNumber = new SelectList(db.Adm, "AdmNumber", "AdmNumber");
            return PartialView();
        }

        // POST: Shops/Create
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Shop shop)
        {
            if (ModelState.IsValid)
            {
                int id = ((Adm)Session["adm"]).AdmNumber;
                var adms = db.Adm.Find(id);

                string sql = "insert into Shop(ShopName,District,ShopAddress,ShopTime,Phone,Web,Outlet,WIFI,LimitedTime,"+
                "IsOrder,AdmNumber,Closed)values(@ShopName,@District,@ShopAddress,@ShopTime,@Phone,@Web,@Outlet,@WIFI,"+
                "@LimitedTime,@IsOrder,@AdmNumber,@Closed)";

                List<SqlParameter> list = new List<SqlParameter>()
                {
                    new SqlParameter("ShopName",shop.ShopName),
                    new SqlParameter("District",shop.District),
                    new SqlParameter("ShopAddress",shop.ShopAddress),
                    new SqlParameter("ShopTime",shop.ShopTime),
                    new SqlParameter("Phone",shop.Phone),
                    new SqlParameter("Web",shop.Web),
                    new SqlParameter("Outlet",shop.Outlet),
                    new SqlParameter("WIFI",shop.WIFI),
                    new SqlParameter("LimitedTime",shop.LimitedTime),
                    new SqlParameter("IsOrder",shop.IsOrder),
                    new SqlParameter("AdmNumber",adms.AdmNumber),
                    new SqlParameter("Closed",shop.Closed)
                };

                sd.executeSql(sql,list);
                return RedirectToAction("Index");

            }

            ViewBag.AdmNumber = new SelectList(db.Adm, "AdmNumber", "AdmNumber", shop.AdmNumber);
            return View(shop);
        }

        // GET: Shops/Edit/5
        public ActionResult _Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shop shop = db.Shop.Find(id);
            if (shop == null)
            {
                return HttpNotFound();
            }

            ViewBag.AdmNumber = new SelectList(db.Adm, "AdmNumber", "AdmNumber", shop.AdmNumber);
            return PartialView(shop);
        }

        // POST: Shops/Edit/5
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Shop shop)
        {
            if (ModelState.IsValid)
            {
                string sql = "update Shop set ShopName=@ShopName,District=@District,ShopAddress=@ShopAddress,"+
                "ShopTime=@ShopTime,Phone=@Phone,Web=@Web,Outlet=@Outlet,WIFI=@WIFI,LimitedTime=@LimitedTime,"+
                "IsOrder=@IsOrder,UpdateDate=@UpdateDate,Closed=@Closed where ShopNumber=@ShopNumber";

                List<SqlParameter> list = new List<SqlParameter>
                {
                    new SqlParameter("ShopName",shop.ShopName),
                    new SqlParameter("District",shop.District),
                    new SqlParameter("ShopAddress",shop.ShopAddress),
                    new SqlParameter("ShopTime",shop.ShopTime),
                    new SqlParameter("Phone",shop.Phone),
                    new SqlParameter("Web",shop.Web),
                    new SqlParameter("Outlet",shop.Outlet),
                    new SqlParameter("WIFI",shop.WIFI),
                    new SqlParameter("LimitedTime",shop.LimitedTime),
                    new SqlParameter("IsOrder",shop.IsOrder),
                    new SqlParameter("UpdateDate",shop.UpdateDate),
                    new SqlParameter("Closed",shop.Closed),
                    new SqlParameter("ShopNumber",shop.ShopNumber)
                };

                sd.executeSql(sql,list);
                return RedirectToAction("Index");
            }
            
                ViewBag.AdmNumber = new SelectList(db.Adm, "AdmNumber", "AdmNumber", shop.AdmNumber);
                return View(shop);
        }

        // GET: Shops/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shop shop = db.Shop.Find(id);
            if (shop == null)
            {
                return HttpNotFound();
            }
            return View(shop);
        }

        // POST: Shops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Shop shop = db.Shop.Find(id);
            db.Shop.Remove(shop);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        
    }

}

Subject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Mystyle.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    @RenderSection("css", false)
</head>
@*fixed-top*@
<body>
    <div class="navbar navbar-expand-lg navbar-light bg-warning">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("跑咖Cafe'", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <i class="bi bi-cup-fill text-black-50" style="font-size:20px"></i>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse ml-3" id="mainMenu">
                <ul class="navbar-nav mr-auto w-100 mt-1">
                    <li class="nav-item">
                        <a href="@Url.Action("Index","Home")" class="nav-link">咖啡廳清單 <i class="bi bi-clipboard2-heart d-inline-flex"></i></a>
                    </li>
                    
                    <li class="nav-item">
                        <a href="@Url.Action("PostShop","Home")" class="nav-link">新增店家 <i class="bi bi-shop d-inline-flex"></i></a>
                    </li>
                   
                    <li class="nav-item">
                        <a href="@Url.Action("Suggest","Home")" class="nav-link">建議 <i class="bi bi-chat-text-fill d-inline-flex"></i></a>
                    </li>
                    
                                @*<li class="nav-item">
                        <form class="form-inline my-2 my-lg-0" action="https://www.google.com/search">
                            <input class="form-control mr-sm-2" name="q" type="search" placeholder="搜尋咖啡廳" aria-label="Search">
                            <button class="btn btn-light my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                        </form>
                    </li>*@
                    @if (Session["user"] == null)
                    {
                        <li class="nav-item ml-auto">
                            <a href="@Url.Action("Login","Home")" class="nav-link btn btn-light text-dark p-1 pl-2 pr-2"><i class="bi bi-person-circle"></i> 登入/註冊</a>
                        </li>
                    }
                    @if (Session["user"] != null)
                    {
                        <li class="dropdown ml-auto">
                            <button class="btn btn-light dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
                                <i class="bi bi-person-circle"></i> 會員中心
                            </button>
                            <div class="dropdown-menu">
                                @Html.ActionLink("主頁", "UserIndex", "Home", new { area = "" }, new { @class = "dropdown-item" })
                                @*@Html.ActionLink("使用者頁面", "Index", "Home", new { area = "" }, new { @class = "dropdown-item" })*@
                                <div class="dropdown-divider"></div>
                                @Html.ActionLink("登出", "Logout", "Home", new { area = "" }, new { @class = "dropdown-item " })
                            </div>
                        </li>
                        @*<li class="nav-item ml-auto">
                @Html.ActionLink("會員中心", "UserIndex", "Home", null, new { @class = "nav-link" })
            </li>
            <li class="nav-item ml-3">
                @Html.ActionLink("登出", "Logout", "Home", new { area = "" }, new { @class = "nav-link btn btn-light text-dark" })
            </li>*@
                    }
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Cafe'</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

Subject/Views/Shared/_Layout_Adm.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Mystyle.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    @RenderSection("css", false)
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("跑咖Cafe", "AfterLogin", "Adms", new { area = "" }, new { @class = "navbar-brand" })
                <i class="bi bi-cup-fill text-light" style="font-size:20px"></i>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse ml-3" id="mainMenu">
                <ul class="navbar-nav mr-auto w-100">
                    <li class="nav-item dropdown">
                        @Html.ActionLink("用戶管理", "Index", "Users", new { area = "" }, new { @class = "nav-link dropdown-toggle", data_toggle = "dropdown", aria_expanded = "false" })
                        <div class="dropdown-menu">
                            @Html.ActionLink("主頁", "Index", "Users", new { area = "" }, new { @class = "dropdown-item" })
                            <div class="dropdown-divider"></div>
                            @Html.ActionLink("封鎖名單", "Block", "Users", new { area = "" }, new { @class = "dropdown-item" })
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        @Html.ActionLink("店家管理", "Index", "Shops", new { area = "" }, new { @class = "nav-link dropdown-toggle", data_toggle = "dropdown", aria_expanded = "false" })
                        <div class="dropdown-menu">
                            @Html.ActionLink("主頁", "Index", "Shops", new { area = "" }, new { @class = "dropdown-item" })
                            <div class="dropdown-divider"></div>
                            @Html.ActionLink("菜單管理", "Index", "ShopMenus", new { area = "" }, new { @class = "dropdown-item" })
                            @Html.ActionLink("標籤管理", "Index", "ShopTags", new { area = "" }, new { @class = "dropdown-item" })
                            @Html.ActionLink("照片管理", "Index", "ShopImages", new { area = "" }, new { @class = "dropdown-item" })
                            @Html.ActionLink("付款方式管理", "Index", "ShopPays", new { area = "" }, new { @class = "dropdown-item" })
                        </div>
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("付款種類", "Index", "Pays", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item dropdown">
                        @Html.ActionLink("投稿專區", "Index", "PostShops", new { area = "" }, new { @class = "nav-link dropdown-toggle", data_toggle = "dropdown", aria_expanded = "false" })
                        <div class="dropdown-menu">
                            @Html.ActionLink("新店家", "Index", "PostShops", new { area = "" }, new { @class = "dropdown-item" })
                            <div class="dropdown-divider"></div>
                            @Html.ActionLink("建議", "Index", "Suggests", new { area = "" }, new { @class = "dropdown-item" })
                        </div>
                    </li>
                    @*<li class="nav-item">
                        @Html.ActionLink("建議", "Index", "Suggests", new { area = "" }, new { @class = "nav-link" })
                    </li>*@
                    <li class="dropdown ml-auto">
                        <button class="btn btn-light dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
                            管理員
                        </button>
                        <div class="dropdown-menu">
                            @Html.ActionLink("管理員資料", "Index", "Adms", new { area = "" }, new { @class = "dropdown-item" })
                            @Html.ActionLink("使用者頁面", "Index", "Home", new { area = "" }, new { @class = "dropdown-item" })
                            <div class="dropdown-divider"></div>
                            @Html.ActionLink("登出", "Logout", "Adms", new { area = "" }, new { @class = "dropdown-item " })
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Cafe'</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

Subject/Views/Shared/_Layout_Adm_Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Mystyle.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    @RenderSection("css", false)
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a href="@Url.Action("Login","Home")" class="bi bi-arrow-left text-white" style="font-size:18px;"></a>
        <div class="container row mx-auto pl-0">
            <div class="p-2 text-white mx-auto" style="font-size:18px;">登入跑咖Cafe'後台系統</div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Cafe'</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

Subject/Views/Shared/_Layout_User_Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Mystyle.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    @RenderSection("css", false)
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a href="@Url.Action("Index","Home")" class="bi bi-arrow-left text-white" style="font-size:18px;"></a>
        <div class="container row mx-auto pl-0">
            <div class="p-2 text-white mx-auto" style="font-size:18px;">登入跑咖Cafe'會員</div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Cafe'</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

Subject/Views/Shared/_Layout_User_SignUp.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Mystyle.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    @RenderSection("css", false)
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-light bg-light">
        <a href="@Url.Action("Login","Home")" class="bi bi-arrow-left text-dark" style="font-size:18px;"></a>
        <div class="container row mx-auto pl-0">
            <div class="p-2 text-dark mx-auto"  style="font-size:18px;">註冊跑咖Cafe'會員</div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Cafe'</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>