Subject/Models/ShopMenu.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ShopMenu
    {
        [DisplayName("菜單編號")]
        public int MenuNumber { get; set; }

        [DisplayName("會員")]
        public int UserNumber { get; set; }

        [DisplayName("店家")]
        public int ShopNumber { get; set; }

        [DisplayName("品項")]
        [Required(ErrorMessage = "請填寫品項")]
        public string Item { get; set; }

        [DisplayName("價錢")]
        [Required(ErrorMessage = "請填寫價錢")]
        public short Price { get; set; }

        [DisplayName("建立日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> MenuDate { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual Users Users { get; set; }
    }
}

Subject/Controllers/ShopMenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Mvc;
using Subject.Models;

namespace Subject.Controllers
{
    [LoginCheck]
    public class ShopMenusController : Controller
    {
        private SpecialSubjectEntities db = new SpecialSubjectEntities();
        SetData sd= new SetData();

        // GET: ShopMenus
        public ActionResult Index()
        {
            var shopMenu = db.ShopMenu.Include(s => s.Shop).Include(s => s.Users);
            return View(shopMenu.ToList());
        }

        // GET: ShopMenus/Details/5
        public ActionResult _Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ShopMenu shopMenu = db.ShopMenu.Find(id);
            if (shopMenu == null)
            {
                return HttpNotFound();
            }
            return PartialView(shopMenu);
        }

        // GET: ShopMenus/Create
        public ActionResult _Create()
        {
            ViewBag.ShopNumber = new SelectList(db.Shop, "ShopNumber", "ShopName");
            ViewBag.UserNumber = new SelectList(db.Users, "UserNumber", "UserNumber");
            return PartialView();
        }

        // POST: ShopMenus/Create
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ShopMenu shopMenu)
        {
            if (ModelState.IsValid)
            {
                string sql = "insert into ShopMenu(UserNumber,ShopNumber,Item,Price)values(@UserNumber,@ShopNumber,@Item,@Price)";
                List<SqlParameter> list = new List<SqlParameter>
                {
                    new SqlParameter("UserNumber",shopMenu.UserNumber),
                    new SqlParameter("ShopNumber",shopMenu.ShopNumber),
                    new SqlParameter("Item",shopMenu.Item),
                    new SqlParameter("Price",shopMenu.Price)
                };

                sd.executeSql(sql, list);
                return RedirectToAction("Index");
            }

            ViewBag.ShopNumber = new SelectList(db.Shop, "ShopNumber", "ShopName", shopMenu.ShopNumber);
            ViewBag.UserNumber = new SelectList(db.Users, "UserNumber", "UserNumber", shopMenu.UserNumber);
            return View(shopMenu);

        }

        // GET: ShopMenus/Edit/5
        public ActionResult _Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ShopMenu shopMenu = db.ShopMenu.Find(id);
            if (shopMenu == null)
            {
                return HttpNotFound();
            }
            ViewBag.ShopNumber = new SelectList(db.Shop, "ShopNumber", "ShopName", shopMenu.ShopNumber);
            ViewBag.UserNumber = new SelectList(db.Users, "UserNumber", "UserNumber", shopMenu.UserNumber);
            return PartialView(shopMenu);
        }

        // POST: ShopMenus/Edit/5
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ShopMenu shopMenu)
        {
            string sql = "update ShopMenu set UserNumber=@UserNumber,ShopNumber=@ShopNumber,Item=@Item,Price=@Price from ShopMenu " +
                "inner join Shop on ShopMenu.ShopNumber=Shop.ShopNumber " +
                "inner join Users on ShopMenu.UserNumber=Users.UserNumber " +
                "where MenuNumber=@MenuNumber";

            List<SqlParameter> list = new List<SqlParameter>
            {
                new SqlParameter("UserNumber",shopMenu.UserNumber),
                new SqlParameter("ShopNumber",shopMenu.ShopNumber),
                new SqlParameter("Item",shopMenu.Item),
                new SqlParameter("Price",shopMenu.Price),
                new SqlParameter("MenuNumber",shopMenu.MenuNumber)
            };

            try
            {
                sd.executeSql(sql, list);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ViewBag.Msg = ex.Message;
                ViewBag.ShopNumber = new SelectList(db.Shop, "ShopNumber", "ShopName", shopMenu.ShopNumber);
                ViewBag.UserNumber = new SelectList(db.Users, "UserNumber", "UserNumber", shopMenu.UserNumber);
                return View(shopMenu);
            }

        }

        // GET: ShopMenus/Delete/5
        public ActionResult _Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ShopMenu shopMenu = db.ShopMenu.Find(id);
            if (shopMenu == null)
            {
                return HttpNotFound();
            }
            return PartialView(shopMenu);
        }

        // POST: ShopMenus/Delete/5
        [HttpPost, ActionName("_Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ShopMenu shopMenu = db.ShopMenu.Find(id);
            db.ShopMenu.Remove(shopMenu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Subject/Views/ShopMenus/Index.cshtml
@model IEnumerable<Subject.Models.ShopMenu>

@{
    ViewBag.Title = "Index";
}


<h2 class="mt-3 text-center">菜單管理</h2>

<table class="table table-hover table-responsive-lg mt-3">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MenuNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Shop.ShopName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Item)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Users.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuDate)
        </th>
        <th>管理</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MenuNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Shop.ShopName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Item)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Users.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MenuDate)
            </td>
            <td>
                @*<button type="button" id="@item.MenuNumber" class="btn btn-primary btn-sm disabled" data-toggle="modal" data-target="#showEditModal" onclick="getEditData(event)">
                    <i class="bi bi-pencil-square" id="@item.MenuNumber"></i>
                </button>*@
                <button type="button" id="@item.MenuNumber" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#showDeleteModal" onclick="getDeleteData(event)">
                    <i class="bi bi-trash3" id="@item.MenuNumber"></i>
                </button>
            </td>
        </tr>
    }

</table>

<div class="modal fade" id="showEditModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <div class="text-dark mt-2 ml-2"><h5>編輯資料</h5></div>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="showDeleteModal" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <div class="text-dark mt-2 ml-2"><h5>確定要刪除嗎?</h5></div>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        function getEditData(evt) {
            $('#showEditModal .modal-body').load("/ShopMenus/_Edit/" + evt.target.id);
        }

        function getDeleteData(evt) {
            $('#showDeleteModal .modal-body').load("/ShopMenus/_Delete/" + evt.target.id);
        }

    </script>


}

Subject/Views/ShopMenus/_Create.cshtml
@model Subject.Models.ShopMenu

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create","ShopMenus",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserNumber, "UserNumber", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserNumber", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShopNumber, "ShopName", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ShopNumber", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShopNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Item, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Item, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Item, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.MenuDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Subject/Views/ShopMenus/_Delete.cshtml
@model Subject.Models.ShopMenu

@{
    ViewBag.Title = "Delete";
}

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Shop.ShopName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shop.ShopName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm("_Delete","ShopMenus",FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color text-right">
            <input type="submit" value="刪除" class="btn btn-danger" />
        </div>
    }
</div>

Subject/Views/ShopMenus/_Details.cshtml
@model Subject.Models.ShopMenu

@{
    ViewBag.Title = "Details";
}



<div class="card">
    <div class="card-body">
        <div>
            @Html.DisplayNameFor(model => model.Shop.ShopNumber)@Html.DisplayFor(model => model.Shop.ShopNumber)
        </div>
        <div>
            @Html.DisplayNameFor(model => model.Item)@Html.DisplayFor(model => model.Item)
        </div>
        <div>
            @Html.DisplayNameFor(model => model.Price)@Html.DisplayFor(model => model.Price)
        </div>
        <div>
            @Html.DisplayNameFor(model => model.MenuDate)@Html.DisplayFor(model => model.MenuDate)
        </div>
        <div>
            @Html.DisplayNameFor(model => model.Users.UserAccount)@Html.DisplayFor(model => model.Users.UserAccount)
        </div>
    </div>
</div>

Subject/Views/ShopMenus/_Edit.cshtml
@model Subject.Models.ShopMenu

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit","ShopMenus",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MenuNumber)

        <div class="form-group">
            @Html.LabelFor(model => model.UserNumber, "UserNumber", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserNumber", (IEnumerable<SelectListItem>)ViewBag.UserNumber, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShopNumber, "ShopName", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ShopNumber", (IEnumerable<SelectListItem>)ViewBag.ShopNumber, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShopNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Item, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Item, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Item, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.MenuDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="更新" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>