Subject/Models/ShopTag.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ShopTag
    {
        [DisplayName("標籤編號")]
        public int TagNumber { get; set; }

        [DisplayName("會員")]
        public int UserNumber { get; set; }

        [DisplayName("店家")]
        public int ShopNumber { get; set; }

        [DisplayName("標籤內容")]
        [Required(ErrorMessage = "請填寫標籤")]
        public string Tag { get; set; }

        [DisplayName("建立日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> TagDate { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual Users Users { get; set; }
    }
}

Subject/Controllers/ShopTagsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Subject.Models;

namespace Subject.Controllers
{
    [LoginCheck]
    public class ShopTagsController : Controller
    {
        private SpecialSubjectEntities db = new SpecialSubjectEntities();
        SetData sd = new SetData();

        // GET: ShopTags
        public ActionResult Index()
        {
            var shopTag = db.ShopTag.Include(s => s.Shop).Include(s => s.Users);
            return View(shopTag.ToList());
        }

        // GET: ShopTags/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ShopTag shopTag = db.ShopTag.Find(id);
            if (shopTag == null)
            {
                return HttpNotFound();
            }
            return View(shopTag);
        }

        // GET: ShopTags/Create
        public ActionResult _Create()
        {
            ViewBag.ShopNumber = new SelectList(db.Shop, "ShopNumber", "ShopName");
            ViewBag.UserNumber = new SelectList(db.Users, "UserNumber", "UserNumber");
            return PartialView();
        }

        // POST: ShopTags/Create
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ShopTag shopTag)
        {
            if (ModelState.IsValid)
            {
                string sql = "insert into ShopTag(UserNumber,ShopNumber,Tag)values(@UserNumber,@ShopNumber,@Tag)";
                List<SqlParameter> list = new List<SqlParameter>
                {
                    new SqlParameter("UserNumber",shopTag.UserNumber),
                    new SqlParameter("ShopNumber", shopTag.ShopNumber),
                    new SqlParameter("Tag", shopTag.Tag)
                };

                sd.executeSql(sql, list);
                return RedirectToAction("Index");
            }

            ViewBag.ShopNumber = new SelectList(db.Shop, "ShopNumber", "ShopName", shopTag.ShopNumber);
            ViewBag.UserNumber = new SelectList(db.Users, "UserNumber", "UserNumber", shopTag.UserNumber);
            return View(shopTag);
        }


        // GET: ShopTags/Edit/5
        public ActionResult _Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ShopTag shopTag = db.ShopTag.Find(id);
            if (shopTag == null)
            {
                return HttpNotFound();
            }
            ViewBag.ShopNumber = new SelectList(db.Shop, "ShopNumber", "ShopName", shopTag.ShopNumber);
            ViewBag.UserNumber = new SelectList(db.Users, "UserNumber", "UserNumber", shopTag.UserNumber);
            return PartialView(shopTag);
        }

        // POST: ShopTags/Edit/5
        // 若要避免過量張貼攻擊，請啟用您要繫結的特定屬性。
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ShopTag shopTag)
        {
            string sql = "update ShopTag set UserNumber=@UserNumber,ShopNumber=@ShopNumber,Tag=@Tag from ShopTag " +
                "inner join Shop on ShopTag.ShopNumber=Shop.ShopNumber " +
                "inner join Users on ShopTag.UserNumber=Users.UserNumber " +
                "where TagNumber=@TagNumber";

            List<SqlParameter> list = new List<SqlParameter>
            {
                new SqlParameter("UserNumber",shopTag.UserNumber),
                new SqlParameter("ShopNumber",shopTag.ShopNumber),
                new SqlParameter("Tag",shopTag.Tag),
                new SqlParameter("TagNumber",shopTag.TagNumber)
            };

            try
            {
                sd.executeSql(sql,list);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ViewBag.Msg=ex.Message;
                ViewBag.ShopNumber = new SelectList(db.Shop, "ShopNumber", "ShopName", shopTag.ShopNumber);
                ViewBag.UserNumber = new SelectList(db.Users, "UserNumber", "UserNumber", shopTag.UserNumber);
                return View(shopTag);
            }

        }

        // GET: ShopTags/Delete/5
        public ActionResult _Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ShopTag shopTag = db.ShopTag.Find(id);
            if (shopTag == null)
            {
                return HttpNotFound();
            }
            return PartialView(shopTag);
        }

        // POST: ShopTags/Delete/5
        [HttpPost, ActionName("_Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ShopTag shopTag = db.ShopTag.Find(id);
            db.ShopTag.Remove(shopTag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Subject/Views/ShopTags/Create.cshtml
@model Subject.Models.ShopTag

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ShopTag</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserNumber, "UserNumber", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserNumber", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShopNumber, "ShopNumber", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ShopNumber", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShopNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TagDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TagDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TagDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Subject/Views/ShopTags/Details.cshtml
@model Subject.Models.ShopTag

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ShopTag</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TagDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TagDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Shop.ShopName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shop.ShopName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Users.UserAccount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Users.UserAccount)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TagNumber }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Subject/Views/ShopTags/Edit.cshtml
@model Subject.Models.ShopTag

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ShopTag</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TagNumber)

        <div class="form-group">
            @Html.LabelFor(model => model.UserNumber, "UserNumber", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserNumber", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShopNumber, "ShopNumber", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ShopNumber", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShopNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TagDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TagDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TagDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Subject/Views/ShopTags/Index.cshtml
@model IEnumerable<Subject.Models.ShopTag>

@{
    ViewBag.Title = "Index";
}

<h2 class="mt-3 text-center">標籤管理</h2>

<table class="table table-hover table-responsive-lg mt-3">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TagNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Shop.ShopName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tag)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Users.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TagDate)
        </th>
        <th>
            管理
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TagNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Shop.ShopName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tag)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Users.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TagDate)
            </td>
            <td>
                @*<button type="button" id="@item.TagNumber" class="btn btn-primary btn-sm disabled" data-toggle="modal" data-target="#showEditModal" onclick="getEditData(event)">
                    <i class="bi bi-pencil-square" id="@item.TagNumber"></i>
                </button>*@
                <button type="button" id="@item.TagNumber" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#showDeleteModal" onclick="getDeleteData(event)">
                    <i class="bi bi-trash3" id="@item.TagNumber"></i>
                </button>
            </td>
        </tr>
    }

</table>

<div class="modal fade" id="showDeleteModal" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <div class="text-dark mt-2 ml-2"><h5>確定要刪除嗎?</h5></div>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        function getDeleteData(evt) {
            $('#showDeleteModal .modal-body').load("/ShopTags/_Delete/" + evt.target.id);
        }

    </script>


}

Subject/Views/ShopTags/_Create.cshtml
@model Subject.Models.ShopTag

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create","ShopTags",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserNumber, "UserNumber", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserNumber", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShopNumber, "ShopName", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ShopNumber", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShopNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tag, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.TagDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TagDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TagDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增" class="btn btn-default" />
            </div>
        </div>
    </div>
}



<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Subject/Views/ShopTags/_Delete.cshtml
@model Subject.Models.ShopTag

@{
    ViewBag.Title = "Delete";
}

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Shop.ShopName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shop.ShopName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tag)
        </dd>

    </dl>

    @using (Html.BeginForm("_Delete","ShopTags",FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color text-right">
            <input type="submit" value="刪除" class="btn btn-danger" /> 
        </div>
    }
</div>

Subject/Views/ShopTags/_Edit.cshtml
@model Subject.Models.ShopTag

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit","ShopTags",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TagNumber)

        <div class="form-group">
            @Html.LabelFor(model => model.UserNumber, "UserNumber", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserNumber", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShopNumber, "ShopName", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ShopNumber", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShopNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tag, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.TagDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TagDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TagDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="更新" class="btn btn-default" />
            </div>
        </div>
    </div>
}



<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>